export interface EquipmentInvProps{
    SystemId: number, 
    EmployeeName: string,
    EmployeeId: string,
    Department: string,
    Area: number,
    Section: string,
    Designation: string,
    EqType: string,
    AssetTag: string,
    SerialNumber: string, 
    Brand: string,
    Model: string,
    Batch: string,
    Year_Acquired: string,
    Year_Issued: string, 
    EndofWarranty: string,
    ForReplacementYear: string,
    Remarks: string,
    Added_By: string,
    Date_Added: string,
    Modified_By: string, 
    Date_Modified: string, 
    AccountedTo: string,
    Others: string,
    IRTransaction_Number: string,
    Storage: string,
    Memory: string,
    Processor: string,
    OS: string,
    Status:string,
}